[package]
name = "runner-token-tool"
version = "1.0.0"
authors = ["Riley Flynn <riley@rileyflynn.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
